language: haskell

script:
  - cabal configure --enable-benchmarks && cabal build && cabal bench

before_install:
  - cabal update

install:
  - cabal install --only-dependencies --enable-benchmarks
  
notifications:
  email:
      - alpmestan@gmail.com
  irc: "irc.freenode.org#haskell-math"
